import base64
import logging
import secrets
from urllib.parse import urljoin

from odoo import api, fields, models, _
from odoo.exceptions import UserError
from werkzeug.security import generate_password_hash

from ..controllers.auth import TOKEN_STATUS_HTTPBASIC_URL

_logger = logging.getLogger(__name__)


class HttpBasicCredentialsWizard(models.TransientModel):
    _name = 'ik.httpbasic_credentials_wizard'
    _description = 'HTTP Basic Credentials Generation Wizard'

    # Link to the token being configured
    token_id = fields.Many2one('ik.api_auth_token', required=True, readonly=True)

    # Input fields
    username = fields.Char(
        string="Username",
        help="Leave empty to auto-generate"
    )
    password = fields.Char(
        string="Password",
        help="Leave empty to auto-generate secure password"
    )

    # Display fields (computed after generation)
    generated_username = fields.Char(
        string="Generated Username",
        readonly=True
    )
    generated_password = fields.Char(
        string="Generated Password",
        readonly=True
    )
    auth_header = fields.Char(
        string="Authorization Header",
        readonly=True,
        help="Base64 encoded credentials for Authorization header"
    )
    curl_command = fields.Text(
        string="Test cURL Command",
        readonly=True
    )

    # State management
    state = fields.Selection([
        ('input', 'Input Credentials'),
        ('display', 'Display Generated')
    ], default='input', readonly=True)

    @api.model
    def default_get(self, fields_list):
        """Initialize wizard with current token data"""
        result = super().default_get(fields_list)

        # Get token from context
        token_id = self.env.context.get('default_token_id')
        if token_id:
            token_obj = self.env['ik.api_auth_token'].browse(token_id)
            if token_obj.exists() and token_obj.token_type == 'httpbasicauth':
                # Pre-fill username if it exists
                if token_obj.httpbasicauth_username:
                    result['username'] = token_obj.httpbasicauth_username
                result['token_id'] = token_id

        return result

    def generate_credentials(self):
        """Generate HTTP Basic authentication credentials"""
        self.ensure_one()

        if not self.token_id or self.token_id.token_type != 'httpbasicauth':
            raise UserError(_("Invalid token for HTTP Basic authentication"))

        # Generate username if not provided
        username = self.username.strip() if self.username else f"user_{secrets.token_hex(8)}"

        # Validate username uniqueness (excluding current token)
        existing_token = self.env['ik.api_auth_token'].search([
            ('httpbasicauth_username', '=', username),
            ('id', '!=', self.token_id.id)
        ])
        if existing_token:
            raise UserError(_("Username '%s' is already in use. Please choose a different username.") % username)

        # Generate password if not provided
        password = self.password.strip() if self.password else secrets.token_hex(16)

        if not password:
            raise UserError(_("Password cannot be empty"))

        # Basic password validation
        if len(password) < 8:
            raise UserError(_("Password must be at least 8 characters long"))

        # Hash password for storage
        password_hash = generate_password_hash(password)

        # Update the token record
        self.token_id.write({
            'httpbasicauth_username': username,
            'httpbasicauth_password_hash': password_hash,
        })

        # Generate authorization header
        credentials = f"{username}:{password}"
        encoded_credentials = base64.b64encode(credentials.encode()).decode()
        auth_header = f"Basic {encoded_credentials}"

        # Generate cURL command
        curl_command = self._generate_curl_command(username, password)

        # Update wizard state and display fields
        self.write({
            'state': 'display',
            'generated_username': username,
            'generated_password': password,
            'auth_header': auth_header,
            'curl_command': curl_command,
        })

        # Log security event
        self.token_id.write({
            'security_log': f"{fields.Datetime.now().isoformat()}: HTTP Basic credentials regenerated by {self.env.user.name}\n{self.token_id.security_log or ''}"
        })

        return self._reopen_wizard()

    def _generate_curl_command(self, username, password):
        """Generate test cURL command with the new credentials"""
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        if not base_url:
            return "# Configure web.base.url system parameter first"

        httpbasic_url = urljoin(base_url, TOKEN_STATUS_HTTPBASIC_URL)
        credentials = f"{username}:{password}"
        encoded = base64.b64encode(credentials.encode()).decode()

        return f"curl -H 'Authorization: Basic {encoded}' '{httpbasic_url}'"

    def _reopen_wizard(self):
        """Reopen the wizard to show the updated state"""
        return {
            'name': 'Generate HTTP Basic Credentials',
            'type': 'ir.actions.act_window',
            'res_model': 'ik.httpbasic_credentials_wizard',
            'view_mode': 'form',
            'res_id': self.id,
            'target': 'new',
        }

    def confirm_and_close(self):
        """Close the wizard"""
        # Log confirmation in the token's message thread for audit purposes
        #self.token_id.message_post(
        #    body=f"HTTP Basic credentials have been generated and acknowledged by {self.env.user.name}",
        #    subject="Credentials Acknowledged"
        #)

        # Close the wizard window
        return {'type': 'ir.actions.act_window_close'}