import logging
import secrets
from datetime import timedelta
from urllib.parse import urljoin

from odoo import api, fields, models, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


TOKEN_TYPES_LIST = [
    ('oauth_client', "OAuth 2.0 Client Credentials"),
]


class InoukAPIAuthToken(models.Model):
    _inherit = 'ik.api_auth_token'

    # Add OAuth Client to token type selection
    token_type = fields.Selection(
        selection_add=TOKEN_TYPES_LIST,
        ondelete={'oauth_client': 'cascade'}
    )

    # SQL constraints for OAuth client
    _sql_constraints = [
        ('oauth_client_id_uniq',
         "UNIQUE(oauth_client_id)",
         "OAuth Client ID must be unique!")
    ]

    # OAuth Client Credentials specific fields
    oauth_client_id = fields.Char(
        string="Client ID",
        help="OAuth 2.0 Client ID (public identifier)",
        index=True
    )
    oauth_client_secret = fields.Char(
        string="Client Secret",
        help="OAuth 2.0 Client Secret (keep confidential)"
    )
    oauth_token_lifetime = fields.Integer(
        string="Token Lifetime (seconds)",
        default=3600,
        help="Lifetime of generated access tokens (default: 1 hour)"
    )

    # Relation to generated access tokens (header type with Bearer config)
    oauth_generated_token_ids = fields.One2many(
        'ik.api_auth_token',
        'oauth_parent_client_id',
        string="Generated Access Tokens",
        domain=[('token_type', '=', 'header')]
    )

    # Inverse field on Bearer for link to parent OAuth client
    oauth_parent_client_id = fields.Many2one(
        'ik.api_auth_token',
        string="OAuth Client Parent",
        domain=[('token_type', '=', 'oauth_client')],
        ondelete='cascade',
        help="OAuth Client that generated this Bearer token"
    )

    def btn_regenerate_credentials(self):
        """Regenerate OAuth client_id and client_secret."""
        self.ensure_one()

        if self.token_type == 'oauth_client':
            # Generate client_id if empty
            if not self.oauth_client_id:
                self.oauth_client_id = "ikaa_{}".format(secrets.token_urlsafe(16))

            # Always regenerate client_secret
            self.oauth_client_secret = secrets.token_urlsafe(32)
            return True
        else:
            return super().btn_regenerate_credentials()

    def generate_access_token(self):
        """Generate a new header-based Bearer token for this OAuth client.

        Uses 'header' token type (not deprecated 'bearer') with standard
        Bearer configuration: Authorization header + 'Bearer ' prefix.
        """
        self.ensure_one()
        if self.token_type != 'oauth_client':
            raise UserError(_("Can only generate tokens for oauth_client type"))

        expiration = fields.Datetime.now() + timedelta(seconds=self.oauth_token_lifetime)

        # Use 'header' type with Bearer configuration (NOT deprecated 'bearer' type)
        access_token = self.env['ik.api_auth_token'].sudo().create({
            'name': "OAuth Access Token - {}".format(self.name),
            'token_type': 'header',
            'user_id': self.user_id.id,
            # Token value - use inherited generate_credentials_header()
            'static_token': self.generate_credentials_header(),
            # Bearer token configuration
            'header_name': 'Authorization',
            'header_prefix': 'Bearer ',
            'support_url_param': True,
            'url_param_name': 'access_token',
            # Link to parent OAuth client
            'expiration_ts': expiration,
            'oauth_parent_client_id': self.id,
            'enforce_integrity': self.enforce_integrity,
        })
        return access_token

    @api.model
    def _cron_cleanup_expired_oauth_tokens(self):
        """Cleanup expired access tokens generated by OAuth clients.

        Tokens are kept for a configurable period after expiration for auditing.
        The delay is configured via Settings > General Settings > API Auth.
        """
        # Get cleanup delay (default: 168 hours = 7 days)
        delay_hours = int(self.env['ir.config_parameter'].sudo().get_param(
            'inouk_api_auth.oauth_token_cleanup_delay_hours', '168'
        ))
        cleanup_threshold = fields.Datetime.now() - timedelta(hours=delay_hours)

        expired_tokens = self.search([
            ('token_type', '=', 'header'),  # Generated tokens use 'header' type
            ('oauth_parent_client_id', '!=', False),
            ('expiration_ts', '<=', cleanup_threshold),  # Expired + retention delay
        ])
        if expired_tokens:
            _logger.info(
                "Cleaning up %d expired OAuth access tokens (expired > %d hours ago)",
                len(expired_tokens), delay_hours
            )
            expired_tokens.unlink()
        return True

    def compute__oauth_client_test_curl(self):
        """Generate OAuth client credentials curl command for testing."""
        self.ensure_one()
        if not self.oauth_client_id or not self.oauth_client_secret:
            return "# Generate OAuth credentials first"

        _base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        if not _base_url:
            return "# Configure web.base.url first"

        oauth_url = urljoin(_base_url, '/oauth/token')

        return """# Set environment variables:
export IKAA_OAUTH_CLIENT_ID="{client_id}"
export IKAA_OAUTH_CLIENT_SECRET="{client_secret}"

# Request access token
curl -X POST "{oauth_url}" \\
  -d "grant_type=client_credentials" \\
  -d "client_id=$IKAA_OAUTH_CLIENT_ID" \\
  -d "client_secret=$IKAA_OAUTH_CLIENT_SECRET" | jq

# Response: {{"access_token": "...", "token_type": "Bearer", "expires_in": {lifetime}}}""".format(
            client_id=self.oauth_client_id,
            client_secret=self.oauth_client_secret,
            oauth_url=oauth_url,
            lifetime=self.oauth_token_lifetime
        )

    def compute__test_curl(self):
        """Override to handle OAuth client cURL generation."""
        for record in self:
            if record.token_type == 'oauth_client':
                record.test_curl_helper = record.compute__oauth_client_test_curl()
                record.hello_url = None
            else:
                super(InoukAPIAuthToken, record).compute__test_curl()

    def compute__python_examples(self):
        """Generate Python requests examples for OAuth Client Credentials."""
        for record in self:
            if record.token_type == 'oauth_client':
                record.python_examples = record._generate_oauth_python_examples()
            else:
                super(InoukAPIAuthToken, record).compute__python_examples()

    def _generate_oauth_python_examples(self):
        """Generate Python examples HTML for OAuth Client Credentials."""
        if not self.oauth_client_id or not self.oauth_client_secret:
            return "<div style='padding: 20px; color: #ff9800;'><i>Generate OAuth credentials first to see examples</i></div>"

        _base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        if not _base_url:
            return "<div style='padding: 20px; color: #666;'><i>Configure web.base.url system parameter to see examples</i></div>"

        oauth_url = urljoin(_base_url, '/oauth/token')
        mcp_url = urljoin(_base_url, '/mcp')

        return """
        <div style='padding: 10px; font-family: monospace;'>
        <h3 style='color: #2e7bcf; margin-bottom: 15px;'>OAuth 2.0 Client Credentials (SEP-1046)</h3>

        <div style='background: #e3f2fd; padding: 15px; border-radius: 5px; border-left: 4px solid #2196f3; margin-bottom: 15px;'>
            <strong>Setup Instructions:</strong><br/>
            1. Copy your client_id and client_secret from the form fields above<br/>
            2. Set environment variables:<br/>
            <code>export OAUTH_CLIENT_ID="your_client_id"</code><br/>
            <code>export OAUTH_CLIENT_SECRET="your_client_secret"</code>
        </div>

        <h4 style='color: #666; margin-bottom: 10px;'>Step 1: Get Access Token</h4>
        <pre style='background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #2e7bcf; overflow-x: auto;'><code style='color: #333;'>import os
import requests

# Load credentials from environment
client_id = os.environ.get('OAUTH_CLIENT_ID')
client_secret = os.environ.get('OAUTH_CLIENT_SECRET')

# Request access token
response = requests.post(
    "{oauth_url}",
    data={{
        'grant_type': 'client_credentials',
        'client_id': client_id,
        'client_secret': client_secret,
    }}
)

token_data = response.json()
access_token = token_data['access_token']
print(f"Access token obtained, expires in {{token_data['expires_in']}}s")</code></pre>

        <h4 style='color: #666; margin-bottom: 10px; margin-top: 20px;'>Step 2: Use Access Token for MCP</h4>
        <pre style='background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #4caf50; overflow-x: auto;'><code style='color: #333;'># Use the access token for MCP requests
headers = {{
    'Authorization': f'Bearer {{access_token}}',
    'Content-Type': 'application/json',
}}

mcp_request = {{
    'jsonrpc': '2.0',
    'id': '1',
    'method': 'initialize',
    'params': {{
        'protocolVersion': '2024-11-05',
        'clientInfo': {{'name': 'python-client'}}
    }}
}}

response = requests.post("{mcp_url}", headers=headers, json=mcp_request)
print(response.json())</code></pre>

        <div style='margin-top: 30px; padding: 15px; background: #e8f5e8; border-radius: 5px; border-left: 4px solid #4caf50;'>
            <h4 style='color: #2e7d32; margin-bottom: 10px;'>Tips</h4>
            <ul style='color: #2e7d32; margin: 0; padding-left: 20px;'>
                <li>Access tokens expire after {lifetime} seconds</li>
                <li>Request a new token when the current one expires</li>
                <li>Store credentials in environment variables, not in code</li>
                <li>Always use HTTPS in production</li>
            </ul>
        </div>
        </div>
        """.format(
            oauth_url=oauth_url,
            mcp_url=mcp_url,
            lifetime=self.oauth_token_lifetime
        )
